(define (problem pb1)
  (:domain seat-arrangement)
  (:objects A B C D S1 S2 S3)
  (:init
   (not(empty S1))
   (empty S2)
   (not(friend A B))
   (friend C D)
   (friend A D)
   (friend B C)
   (empty S3)
   )
  (:goal (and(seated A) (seated B) (seated C) (seated D) (found S1) (found S2)(found S3)))
)